# Generated by Django 4.2.8 on 2025-11-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_rename_ingredient_id_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
    ]
