# Generated by Django 4.2.8 on 2025-11-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_rename_author_id_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
