# Generated by Django 4.2.8 on 2025-11-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_rename_description_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('шт.', 'штук'), ('мл', 'миллилитры'), ('по вкусу', 'по вкусу'), ('ст. л.', 'столовая ложка'), ('ч. л.', 'чайная ложка'), ('щепотка', 'щепотка'), ('капля', 'капля')], max_length=30, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api_v1.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api_v1.recipe'),
        ),
    ]
