# Generated by Django 5.2.8 on 2025-12-14 08:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_rename_userrecipe_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12340', editable=False, length=5, max_length=10, prefix='s/', unique=True, verbose_name='Короткий ID для ссылки'),
        ),
    ]
