# Generated by Django 5.2.8 on 2025-12-15 12:35

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12340', editable=False, length=5, max_length=10, prefix='/s/', unique=True, verbose_name='Короткий ID для ссылки'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='api_v1.recipe'),
        ),
    ]
