# Generated by Django 5.2.8 on 2025-12-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_alter_recipe_short_url_alter_shoppingcartitem_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorits', to='api_v1.recipe'),
        ),
    ]
